### ISSUE TITLE
Quasiquotation breaks Haddock/GHCi

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#158]
**Original reporter**: _arcatan@<hidden>_

When trying to generate Haddock documentation for any file that uses [quasiquotation](http://www.haskell.org/haskellwiki/Quasiquotation), I get an error message similar to this:

``` haskell
% haddock -o doc -h Main.hs         

During interactive linking, GHCi couldn't find the following symbol:
  Quasi_qq_closure
This may be due to you not asking GHCi to load extra object files,
archives or DLLs needed by your current session.  Restart GHCi, specifying
the missing library using the -L/path/to/object/dir and -lmissinglibname
flags, or simply by naming the relevant files on the GHCi command line.
Alternatively, this link failure might indicate a bug in GHCi.
If you suspect the latter, please send a bug report to:
  glasgow-haskell-bugs@haskell.org
```

GHCi loads the modules fine when invoked manually. I'm using Haddock 2.8.1 and GHC 6.12.3 on OS X 10.6.4. I've attached a trivial quasiquoter (Quasi.hs) and Main.hs which uses it and causes problems for Haddock.

**Comment by lexi-lambda** [comment]
I ran into this today. It seems like it only occurs if `QuasiQuotes` is enabled in a file but `TemplateHaskell` is *not*. Whatever special handling haddock uses for files using `TemplateHaskell` should probably also be applied to files using `QuasiQuotes`.

**Comment by harpocrates** [comment]
@lexi-lambda Could you confirm this has been fixed in Haddock 2.19.0? I was able to replicate on previous versions, but not in 2.19.0.

**Comment by LeventErkok** [comment]
@harpocrates Not sure why this was closed? This issue still seems to be haunting haddock. See #1369
