### ISSUE TITLE
Deprecation messages for re-eported items from other packages get lost

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#223]
**Original reporter**: _sol@<hidden>_

**Comment by gbaz** [comment]
Probably fixed by above merge, but worth confirming..

**Comment by harpocrates** [comment]
Not fixed yet. :/

```haskell
module Temp (readsUnary) where
import Data.Functor.Classes
```

Produces

<img width="730" alt="screen shot 2018-10-27 at 12 34 40 am" src="https://user-images.githubusercontent.com/10766081/47601077-21264e80-d980-11e8-9b79-144662b1d35b.png">

Yet, in `Data.Functor.Classes` we have

<img width="733" alt="screen shot 2018-10-27 at 12 34 31 am" src="https://user-images.githubusercontent.com/10766081/47601089-313e2e00-d980-11e8-82ee-c7a8913327c1.png">

**Comment by harpocrates** [comment]
Fixing this is actually not too difficult:

  * add an `instWarningMap` field to `InstalledInterface`
  * use `ifaceWarningMap` from `Interface` to populate that field

I'm going to hold off on fixing this though, since it would collide with the Hi Haddock changes.

**Comment by hsyl20** [comment]
Issue moved to https://gitlab.haskell.org/ghc/ghc/-/issues/24913

**Comment by hsyl20** [comment]
I believe @luite didn't intend to close this. My commit message says: `Haddock also needs to be fixed: https://github.com/haskell/haddock/issues/223` and it confused github apparently.

As I've already moved the issue upstream (https://gitlab.haskell.org/ghc/ghc/-/issues/24913), we can keep it closed here though.
