### ISSUE TITLE
Comments on GADT constructors

### ISSUE THREAD

**Issue by ghc-mirror** [haskell/haddock#43]
**Original reporter**: _jeanphilippe.bernardy@<hidden>_

eg. this fails:

data I ev w a where
    Returns :: a -> I ev w a
    Binds :: I ev w a -> (a -> I ev w b) -> I ev w b
    Gets :: Ord ev => Maybe ev -> Maybe ev -> I ev w ev 
    -- ^ Accept any character between given bounds. Bound is ignored if @Nothing@.

**Comment by wrengr** [comment]
It's been a year or so since mightybyte asked... so, any progress?

**Comment by 23Skidoo** [comment]
IIUC, this is now fixed and the fix will be in GHC 7.12:

https://ghc.haskell.org/trac/ghc/blog/weekly20150721
https://phabricator.haskell.org/D1086

**Comment by shlevy** [comment]
I don't think this is fixed completely, we can document a constructor itself but not the individual arguments.

**Comment by ntc2** [comment]
Like @shlevy says, this is not fixed. Using Haddock 2.17.3 on GHC 8.0.2, docs on GADT **constructors are supported**, but docs on GADT **constructor arguments are not supported**.

This works:

```haskell
data Test1 where
  -- | This is a test.
  Test1 :: Test1
```

This fails with `parse error on input ‘-- ^ This is a test.’`:

```haskell
data Test2 where
  Test2 :: Test2 -- ^ This is a test.
```

**Comment by harpocrates** [comment]
Fixed in #709.

```haskell
data Foo a where
  -- | doc on Bar
  Bar :: a       -- ^ doc on first argument
      -> a       -- ^ doc on second argument
      -> Foo [a] -- ^ doc on return type
```
