### ISSUE TITLE
Make synopsis scrollable with mouse wheel.

### ISSUE THREAD

**Issue by AndreasPK** [haskell/haddock#989]
Modules with lots of definitions result in a synopsis which is too large to view, but is not scrollable.

For example see https://hackage.haskell.org/package/ghc-8.4.3/docs/CoreUtils.html

**Comment by harpocrates** [comment]
And I've already fixed it with the new theme! 🎉

**Comment by carbolymer** [comment]
Still broken in haddock 2.22.0: https://www.stackage.org/haddock/nightly-2019-03-07/http-conduit-2.3.5/Network-HTTP-Client-Conduit.html#v:method

**Comment by harpocrates** [comment]
The fix has not been released yet (it will be in the upcoming 2.23.0 release bundled with GHC 8.8). Besides, Stackage uses a separate theme. Proof this is fixed:

<img width="854" alt="image" src="https://user-images.githubusercontent.com/10766081/53964541-68e28280-40a4-11e9-8607-3505c7490fc0.png">
